//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nerosoft.Euonia.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nerosoft.Euonia.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot lock mutex with expired state.
        /// </summary>
        internal static string ERROR_CANNOT_LOCK_MUTEX_WITH_EXPIRED_STATE {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_LOCK_MUTEX_WITH_EXPIRED_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be null or empty!.
        /// </summary>
        internal static string ERROR_PARAMETER_CANNOT_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_PARAMETER_CANNOT_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity cannot be set to a value less than Count.
        /// </summary>
        internal static string IDS_CAPACITY_CANNOT_BE_SET_TO_A_VALUE_LESS_THAN_COUNT {
            get {
                return ResourceManager.GetString("IDS_CAPACITY_CANNOT_BE_SET_TO_A_VALUE_LESS_THAN_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity may not be negative.
        /// </summary>
        internal static string IDS_CAPACITY_MAY_NOT_BE_NEGATIVE {
            get {
                return ResourceManager.GetString("IDS_CAPACITY_MAY_NOT_BE_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression.
        /// </summary>
        internal static string IDS_EXPRESSION_IS_NOT_A_MEMBER_ACCESS_EXPRESSION {
            get {
                return ResourceManager.GetString("IDS_EXPRESSION_IS_NOT_A_MEMBER_ACCESS_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given type ({0}) should be instance of {1}.
        /// </summary>
        internal static string IDS_GIVEN_TYPE_SHOULD_BE_INSTANCE_OF_TYPE {
            get {
                return ResourceManager.GetString("IDS_GIVEN_TYPE_SHOULD_BE_INSTANCE_OF_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property.
        /// </summary>
        internal static string IDS_MEMBER_ACCESS_EXPRESSION_DOES_NOT_ACCESS_A_PROPERTY {
            get {
                return ResourceManager.GetString("IDS_MEMBER_ACCESS_EXPRESSION_DOES_NOT_ACCESS_A_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a lambda expression.
        /// </summary>
        internal static string IDS_NOT_A_LAMBDA_EXPRESSION {
            get {
                return ResourceManager.GetString("IDS_NOT_A_LAMBDA_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member access.
        /// </summary>
        internal static string IDS_NOT_A_MEMBER_ACCESS {
            get {
                return ResourceManager.GetString("IDS_NOT_A_MEMBER_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a method call.
        /// </summary>
        internal static string IDS_NOT_A_METHOD_CALL {
            get {
                return ResourceManager.GetString("IDS_NOT_A_METHOD_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string IDS_VALUE_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("IDS_VALUE_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is of incorrect type..
        /// </summary>
        internal static string IDS_VALUE_IS_OF_INCORRECT_TYPE {
            get {
                return ResourceManager.GetString("IDS_VALUE_IS_OF_INCORRECT_TYPE", resourceCulture);
            }
        }
    }
}
