
name: Test

on:
#  push:
#    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x', '6.0.x' ]
        configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET workload
    - name: Install .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore packages
      run: dotnet restore Euonia.sln
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
